name: NovaMissileWarsFinalGame
main: net.novauniverse.games.finalgame.missilewars.NovaFinalMissileWars
description: Novauniverse Missile Wars
version: 1.0
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]

authors: [Zeeraa, NovaUniverse]